// Auto generated by solid-file-router
/* prettier-ignore */
/* eslint-disable */
/* oxfmt-ignore */
/* oxlint-disable */

export {}

declare module 'solid-file-router' {
  interface FileRoutePath {
    '/': never
    '/labs': never
    '/labs/:labId': { $labId: string }
    '/projects': never
    '/projects/:projectId': { $projectId: string }
    '/projects/:projectId/checkpoints/:checkpointId': { $projectId: string; $checkpointId: string }
    '/404': never
  }
}

declare module '@solidjs/router' {
  import type { AnchorProps, NavigateOptions, RouterResponseInit, CustomResponse } from '@solidjs/router'

  type Paths =
    | '/'
    | '/labs'
    | '/labs/:labId'
    | '/projects'
    | '/projects/:projectId'
    | '/projects/:projectId/checkpoints/:checkpointId'
    | '/404'

  export declare function A(props: Omit<AnchorProps, 'href'> & { href: Paths }): JSX.Element
  export interface Navigator {
    (to: Paths, options?: Partial<NavigateOptions>): void;
    (delta: number): void;
  }
  export declare function redirect(url: Paths, init?: number | RouterResponseInit): CustomResponse<never>
}
